### ISSUE TITLE
Speakers/Talks

### ISSUE THREAD

**Issue by pawlean** [paulienuh/ShefCodeFirst_Beginners#1]
**Week 1** - Introduction
**Week 2** - Introduction
**Week 3** - Matt - Git Hub Campus Expert
**Week 4** - Start-Up Weekend
**Week 5** - Student Tech Groups: HackSheffield + MedTech 
**Week 6** - ?
**Week 7** - ?
**Week 8** - Competition 

We don't have to have speakers in every week, but I do think it adds to the dynamic a bit! 😊 I've put down some suggestions for now. I think the hackathon scene/techy scene in the university is important for them to be aware of all the things they can get involved with. 

Add your suggestions ⬇️

**Comment by CaffeinatedDave** [comment]
I know Eve from Startup Weekend Sheffield wanted to come in again, probably before November 17th (as that's when their event is) - can we move HackSheffield/MedTech to a later week, since they're not going to be actively peddling an event?

**Comment by pawlean** [comment]
@CaffeinatedDave Yeah, Christi from USE is coming into the Python class but can't make it to Beginners. I think we should get Eve in for the 7th of November which is Week 4. 

I just remembered that Matt is a GitHub Campus Expert and has lots of cool things to give out! I would suggest that he comes in to talk about what GitHub is, what GitHub Education is and then you would follow on... continuing the session on Git! (Assuming you're leading it!) What do you think?

**Comment by CaffeinatedDave** [comment]
Makes sense to me. Make sure he brings plenty of stickers in though.... And maybe some for the class too 😜

**Comment by pawlean** [comment]
Consider it done! 🚩
