### ISSUE TITLE
ShefCodeFirst.com

### ISSUE THREAD

**Issue by pawlean** [paulienuh/ShefCodeFirst_Beginners#4]
Currently to do:

- [ ] Contact any successful alumni to put on the website

- [ ]  Organiser/ambassador alumni -> WE CANT FORGET SOPHIA

- [x]  Python projects. So far no luck right now, but we're working on making it better this term.

**Comment by CaffeinatedDave** [comment]
- [x] Write blog posts / show them on the site

**Comment by CaffeinatedDave** [comment]
(To be fair, you should probably open these as issues on https://github.com/CaffeinatedDave/shefcodefirst instead... though the "help wanted" tag is useful!)

**Comment by pawlean** [comment]
@CaffeinatedDave - I've written loads about CFG here: http://pawlean.com/category/tech/code-first-girls/

Is there a way to get all the posts from that link and display them on the site? Like an RSS feed or whatever? xD
